# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='epnm_info',
        ),
    ]
