# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_ui', '0002_delete_epnm_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='epnm_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
